[allowlist]
description = "Allowlist for known false positives"
paths = [
    '''\.git/''',
    '''\.github/''',
    '''\.env\.example''',
    '''README\.md''',
]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|apikey|secret)['"]?\s*[:=]\s*['"]?([a-zA-Z0-9]{32,45})['"]?'''
tags = ["key", "API", "generic"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["key", "AWS"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws[_-]?(?:secret[_-]?)?access[_-]?key[_-]?(?:id)?['"]?\s*[:=]\s*['"]?[A-Za-z0-9/+=]{40}['"]?'''
tags = ["key", "AWS"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN[^-]+PRIVATE KEY-----'''
tags = ["key", "cryptographic"]

[[rules]]
id = "password-in-code"
description = "Password in code"
regex = '''(?i)(password|passwd|pwd)['"]?\s*[:=]\s*['"]?[^'"]{8,}['"]?'''
tags = ["password", "credentials"]

[[rules]]
id = "database-url"
description = "Database URL with credentials"
regex = '''(?i)(mongodb|mysql|postgresql|redis)://[^:]+:[^@]+@'''
tags = ["database", "credentials"]

[[rules]]
id = "jwt-secret"
description = "JWT Secret"
regex = '''(?i)(jwt[_-]?secret|jwt[_-]?key)['"]?\s*[:=]\s*['"]?[a-zA-Z0-9]{32,}['"]?'''
tags = ["key", "JWT"]

[[rules]]
id = "oauth-secret"
description = "OAuth Secret"
regex = '''(?i)(oauth[_-]?secret|oauth[_-]?key)['"]?\s*[:=]\s*['"]?[a-zA-Z0-9]{32,}['"]?'''
tags = ["key", "OAuth"]

[[rules]]
id = "ssh-private-key"
description = "SSH Private Key"
regex = '''-----BEGIN[^-]+PRIVATE KEY-----[^-]+-----END[^-]+PRIVATE KEY-----'''
tags = ["key", "SSH"]

[[rules]]
id = "encryption-key"
description = "Encryption Key"
regex = '''(?i)(encryption[_-]?key|encrypt[_-]?key)['"]?\s*[:=]\s*['"]?[a-zA-Z0-9]{32,}['"]?'''
tags = ["key", "encryption"] 